"""Added column to sell table to allow differentiation from posts for delete function

Revision ID: 0f9d9d9b88ba
Revises: 9c5415990e77
Create Date: 2024-05-19 16:26:58.379434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9d9d9b88ba'
down_revision = '9c5415990e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
