"""Deleted hello column in db

Revision ID: 933a5145f9f0
Revises: e25789902559
Create Date: 2024-05-19 23:35:22.883685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933a5145f9f0'
down_revision = 'e25789902559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hello')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hello', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
