"""Adding claimed column to Post table so logged in user claimed bounties or not

Revision ID: 9c5415990e77
Revises: ff4d1c479184
Create Date: 2024-05-19 13:37:50.662287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5415990e77'
down_revision = 'ff4d1c479184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('claimed')

    # ### end Alembic commands ###
